name: Windows Build and Packaging

on:
  push:
    branches: [main]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Install PyInstaller
        run: pip install pyinstaller
      - name: Build Executable
        run: pyinstaller --noconsole --onefile task_manager.py
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: task-manager-exe
          path: dist/task_manager.exe
          
  release:
    needs: build-windows
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to create a release and push tags

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: task-manager-exe

      - name: Create a GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "Release"  
          files: task_manager.exe
          name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
